package com.winginrian.hibernate.entity;
// Generated 2019-3-19 23:02:59 by Hibernate Tools 5.2.11.Final

import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 * Home object for domain model class Workflowwebserviceinputmapping.
 * @see com.winginrian.hibernate.entity.Workflowwebserviceinputmapping
 * @author Hibernate Tools
 */
@Stateless
public class WorkflowwebserviceinputmappingHome {

	private static final Log log = LogFactory.getLog(WorkflowwebserviceinputmappingHome.class);

	@PersistenceContext
	private EntityManager entityManager;

	public void persist(Workflowwebserviceinputmapping transientInstance) {
		log.debug("persisting Workflowwebserviceinputmapping instance");
		try {
			entityManager.persist(transientInstance);
			log.debug("persist successful");
		} catch (RuntimeException re) {
			log.error("persist failed", re);
			throw re;
		}
	}

	public void remove(Workflowwebserviceinputmapping persistentInstance) {
		log.debug("removing Workflowwebserviceinputmapping instance");
		try {
			entityManager.remove(persistentInstance);
			log.debug("remove successful");
		} catch (RuntimeException re) {
			log.error("remove failed", re);
			throw re;
		}
	}

	public Workflowwebserviceinputmapping merge(Workflowwebserviceinputmapping detachedInstance) {
		log.debug("merging Workflowwebserviceinputmapping instance");
		try {
			Workflowwebserviceinputmapping result = entityManager.merge(detachedInstance);
			log.debug("merge successful");
			return result;
		} catch (RuntimeException re) {
			log.error("merge failed", re);
			throw re;
		}
	}

	public Workflowwebserviceinputmapping findById(Integer id) {
		log.debug("getting Workflowwebserviceinputmapping instance with id: " + id);
		try {
			Workflowwebserviceinputmapping instance = entityManager.find(Workflowwebserviceinputmapping.class, id);
			log.debug("get successful");
			return instance;
		} catch (RuntimeException re) {
			log.error("get failed", re);
			throw re;
		}
	}
}
