package com.winginrian.hibernate.dao;
// Generated 2019-3-19 23:18:13 by Hibernate Tools 5.2.11.Final


import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 * Home object for domain model class Processpersons.
 * @see com.winginrian.hibernate.dao.Processpersons
 * @author Hibernate Tools
 */
@Stateless
public class ProcesspersonsHome {

    private static final Log log = LogFactory.getLog(ProcesspersonsHome.class);

    @PersistenceContext private EntityManager entityManager;
    
    public void persist(Processpersons transientInstance) {
        log.debug("persisting Processpersons instance");
        try {
            entityManager.persist(transientInstance);
            log.debug("persist successful");
        }
        catch (RuntimeException re) {
            log.error("persist failed", re);
            throw re;
        }
    }
    
    public void remove(Processpersons persistentInstance) {
        log.debug("removing Processpersons instance");
        try {
            entityManager.remove(persistentInstance);
            log.debug("remove successful");
        }
        catch (RuntimeException re) {
            log.error("remove failed", re);
            throw re;
        }
    }
    
    public Processpersons merge(Processpersons detachedInstance) {
        log.debug("merging Processpersons instance");
        try {
            Processpersons result = entityManager.merge(detachedInstance);
            log.debug("merge successful");
            return result;
        }
        catch (RuntimeException re) {
            log.error("merge failed", re);
            throw re;
        }
    }
    
    public Processpersons findById( Integer id) {
        log.debug("getting Processpersons instance with id: " + id);
        try {
            Processpersons instance = entityManager.find(Processpersons.class, id);
            log.debug("get successful");
            return instance;
        }
        catch (RuntimeException re) {
            log.error("get failed", re);
            throw re;
        }
    }
}

